# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20180419_1643'),
        ('variable', '0002_auto_20180131_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['est_id']},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['uni_id']},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['var_id']},
        ),
        migrations.AddField(
            model_name='control',
            name='sen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.Sensor', verbose_name='Sensor'),
        ),
    ]
