# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0021_auto_20180316_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacion',
            options={'ordering': ('-imp_fecha',)},
        ),
    ]
